


source=~/.local/share/ambxst/hyprland.conf
monitor=,preferred,auto,1

env = XDG_MENU_PREFIX,arch-

$mainMod = SUPER
$fileManager = dolphin

input {
    sensitivity = 1.0 
    accel_profile = flat 
    touchpad {
         natural_scroll = true
    }
}

bind = $mainMod SHIFT, S, exec, bash -c 'FILE=~/Pictures/Screenshots/Screenshot_$(date +"%Y-%m-%d_%H%M%S").png && grim -g "$(slurp)" "$FILE" && wl-copy < "$FILE" && notify-send "Chụp màn hình" "Đã lưu vùng chọn"'
bind = , Print, exec, bash -c 'FILE=~/Pictures/Screenshots/Screenshot_$(date +"%Y-%m-%d_%H%M%S").png && grim -g "$(slurp)"  "$FILE" && wl-copy < "$FILE" && notify-send "Chụp màn hình" "Đã lưu toàn màn hình và copy vào Clipboard"'

bind = $mainMod, E, exec, $fileManager
bind = $mainMod, up, fullscreen, 1
bind = $mainMod, down, togglefloating


exec-once = hypridle

exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
#windowrule = float 1, match:class ^(google-chrome)$
#windowrule = float 1, match:class ^(.*)$
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Clipboard Manager Rules & Hotkeys
windowrule = float 1, match:class ^(clipboard)$
windowrule = size 400 600, match:class ^(clipboard)$
windowrule = center 1, match:class ^(clipboard)$
windowrule = pin 1, match:class ^(clipboard)$
#windowrule = stayfocused true, match:class ^(clipboard)$
bind = $mainMod SHIFT, V, exec, clipboard

# File / Folder Picker Rules
windowrule = float 1, match:class ^([Xx]dg-desktop-portal-gtk)$
windowrule = size 900 650, match:class ^([Xx]dg-desktop-portal-gtk)$
windowrule = center 1, match:class ^([Xx]dg-desktop-portal-gtk)$


exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = wl-clip-persist --clipboard regular


exec-once = sleep 2 && fcitx5 -d --replace
env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx

env = SDL_IM_MODULE,fcitx
env = GLFW_IM_MODULE,fcitx
