general {
    lock_cmd = /home/dev/.local/src/ambxst/cli.sh lock
    before_sleep_cmd = loginctl lock-session & sleep 1    # Ép khóa màn hình TRƯỚC KHI sleep và chờ render
    after_sleep_cmd = hyprctl dispatch dpms on  # Bật lại màn hình mượt mà khi wake up
}

listener {
    timeout = 300                               # 5 phút (300s) không xài máy
    on-timeout = loginctl lock-session          # Tự động khóa màn hình
}

listener {
    timeout = 330                               # 5.5 phút
    on-timeout = hyprctl dispatch dpms off      # Tắt hẳn tín hiệu màn hình để tiết kiệm pin
    on-resume = hyprctl dispatch dpms on        # Bật lại khi có thao tác
}
